language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
  - '8'
before_install:
  - npm install -g yarn
install:
  - yarn install
before_script:
  - yarn build
script:
  - yarn lint
  - yarn test
