language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '11'
before_install:
  - npm install -g yarn codecov
install:
  - yarn install
before_script: yarn greenkeeper-lockfile-update
script:
  - yarn commitlint-travis
  - yarn lint
  - yarn test
  - codecov
after_script: yarn greenkeeper-lockfile-upload
after_success: yarn semantic-release
